-- Initial content for Sunrise Photo Studio, generated from the static site (seed files, films JSON, blog MDX).
-- Safe to run once on an empty database: psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f supabase/seeds/0001_content.sql
begin;

insert into public.admins (user_id, email)
select id, email from auth.users where lower(email) = 'gitashrestha0806@gmail.com'
on conflict (user_id) do nothing;

insert into public.site_settings (
  id, name, alternate_name, name_ne, tagline, tagline_ne, description, footer_blurb, studio_blurb,
  phone, whatsapp, email, street, locality, district, region, country, country_code, address_line, address_line_ne,
  maps_url, area_served, facebook_url, youtube_url, youtube_channel_id, default_title
) values (
  1, 'Sunrise Photo Studio', 'Sunrise Digital Photo Studio', 'सनराइज फोटो स्टुडियो',
  'Photos and films for the days you''ll want to relive', 'तपाईंका खुसीका पलहरू, सधैंका लागि',
  'Sunrise Photo Studio in Arjunchaupari, Syangja photographs and films weddings, pasni, bratabandha and family celebrations, and prints premium albums, photo frames and canvas prints.',
  'Weddings, pasni, bratabandha and family celebrations, photographed and filmed in Syangja. Albums, frames and prints made in the studio.',
  'A photo and film studio in Arjunchaupari, Syangja. We photograph and film weddings, pasni, bratabandha and family celebrations across the district, and print what we shoot.',
  '+977 984-6160675', '9779866060450', 'mahendrastha675@gmail.com',
  'Arjunchaupari Rural Municipality-5', 'Arjunchaupari', 'Syangja', 'Gandaki Province', 'Nepal', 'NP',
  'Arjunchaupari-5, Syangja, Nepal', 'अर्जुनचौपारी-५, स्याङ्जा',
  'https://www.google.com/maps/search/?api=1&query=Arjunchaupari%2C+Syangja%2C+Nepal',
  array['Arjunchaupari', 'Panchamul', 'Walling', 'Syangja']::text[],
  'https://www.facebook.com/Sunrisephotostudio675', 'https://www.youtube.com/@sunrisephotostudio3135',
  'UCgLL5B9pQnV7fbme0wYgBUQ', 'Sunrise Photo Studio: wedding photos, films and prints in Syangja'
) on conflict (id) do nothing;

insert into public.pages (key) values ('home'), ('services'), ('prints'), ('films'), ('blogs'), ('about'), ('contact'), ('privacy')
on conflict (key) do nothing;

insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', '2Pn9Ibh7qiI', '/images/films/2Pn9Ibh7qiI.webp', '/images/films/og/2Pn9Ibh7qiI.jpg', 1280, 720, 'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoQAAkAA4BaJQBOgB0kCD8IIAAA/uJ9jfKIkes1v9FB4Phv8SYi62BVo56boUCbWVmWRSkmBcx2wAT377IpUjPHz1W1aej4MFRAvgqNabUVbztsmvV3ie0AAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', '2thTrQR3pec', '/images/films/2thTrQR3pec.webp', '/images/films/og/2thTrQR3pec.jpg', 1080, 720, 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQAAsAA4BaJbACdAEPevUBbWgA/ietl0bdFpZN5pRRY8OOdPFwUjAz9MYdH6HmJcE5Itz87lpxfkGQT2WGu8zDq2RcSHp/OeP5ugcY3IJGnVCpZeQ+n1BSIMAhRigAAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', '3mqD0s53Lvg', '/images/films/3mqD0s53Lvg.webp', '/images/films/og/3mqD0s53Lvg.jpg', 1278, 720, 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAkAA4BaJbACdAYulj5UB0QAAP1QSn+4G+tR8K1pwgMjAXsIpnQy8ib88lltlRpifoYefq6dPLAwCbywJTooJ6c6/3bGe1m97QfiiG/pqj7CuGPn2ymcVRIQAAAA', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', '66Cd8aeqWLQ', '/images/films/66Cd8aeqWLQ.webp', '/images/films/og/66Cd8aeqWLQ.jpg', 1278, 720, 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAQCdASoQAAkAA4BaJbACdACb5vJAAPulg808Y1txO03afMeRVav1X5CpYou//9MMNzDNm/bFt+56gmyPiA59ad7zryafS+w4kBuGwmE/I9FJUhFQIHNCQomOWJKWPHD1aMLJ1mw7gAAA', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'BwOaEbbiVTc', '/images/films/BwOaEbbiVTc.webp', '/images/films/og/BwOaEbbiVTc.jpg', 1068, 720, 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAsAA4BaJbACdAC8hnw881gA/u0JLK+sWk3HDqzTz3lFX4TMj127NGLza843ptsYGYFz4WRKvaT8DMMTA8Zrd2bMofOrOd5pMeiDz6344z7qw111f7xxruJP/l2/KjjDgAAA', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'D8QMlYCuBeA', '/images/films/D8QMlYCuBeA.webp', '/images/films/og/D8QMlYCuBeA.jpg', 1080, 720, 'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAsAA4BaJbACdAD0oGO5O4BAAP66cMyKcD4qZ8+eVJHoDKd1JcDyquDinfOilX918vTEfkoA3v15CSEnm3kshc2IWdDO23Tq65lp4IQ38Rrl6gKBr43bNtv63uY7xwSnHS1XAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'GTBeZRAIcWQ', '/images/films/GTBeZRAIcWQ.webp', '/images/films/og/GTBeZRAIcWQ.jpg', 1280, 720, 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJZgCdADjMRuHZAD2KrsayxTjLKLjX+D03Q27qEZPl7qRhETwpOz+jZY6TrI1CflnBAjb50KHUY15eSmW6n/5tOkWXlr5cbskAA==', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'QZtJ6EMi_vk', '/images/films/QZtJ6EMi_vk.webp', '/images/films/og/QZtJ6EMi_vk.jpg', 480, 720, 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoLABAAA4BaJbAC7H8AE13B2A49oAD+5EpECpThsm6wCZOiMwbC68aStxSKEUlt70RfHzfg27Abavb/nC+Bg4+IxwZpe00lUKJJgFJmaPgQApQ7vdtqnuH4TJ/h6ab0AAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'Rk2D0cbQK34', '/images/films/Rk2D0cbQK34.webp', '/images/films/og/Rk2D0cbQK34.jpg', 1280, 720, 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdAECupVMAAD+v8ZGEt1NA/Dhr6QsP3Owm03fatJP38CfHUV+YsFcdCuh0gm8iwwmEHrmVpPVjAbRpipkAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'TXM4IabFgUk', '/images/films/TXM4IabFgUk.webp', '/images/films/og/TXM4IabFgUk.jpg', 1278, 720, 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJbACdAEfpwOZUUT4AP7omzFDFhZ0eBVF+SkK33tcJeMuIL0c85Nec6631vyOn2veWXoBqGv7Q/QkyJWmzR3NqTt8AAAA', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'YVc6GEgr9uQ', '/images/films/YVc6GEgr9uQ.webp', '/images/films/og/YVc6GEgr9uQ.jpg', 1280, 512, 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAYAA4BaJbACdADp5orRVoAA/P38YKk/7HoC7CgONb+ES47vKvVDOxSM64o/2N0Rbc3d8aiH9lQMzlePtYgHScyRgW4m4zZS1yjZH7IwnP4P/BPalJqkXwC5n9DcUhBQAAAA', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'cmmLJ-wB324', '/images/films/cmmLJ-wB324.webp', '/images/films/og/cmmLJ-wB324.jpg', 1080, 720, 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoQAAsAA4BaJbACdAYv1whvhN+4gAsAAP7miCflrxhK4gOSBdxn0DfoXm9CT46rMYdeCPpUSoPdREoJSYKG6OqOq/XyblvvZqKpIELKsXKcAjL8ZeVW0Gfx48UzkciHEAAAAA==', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'nqMUJ7J7qTg', '/images/films/nqMUJ7J7qTg.webp', '/images/films/og/nqMUJ7J7qTg.jpg', 1080, 720, 'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAsAA4BaJbACdAEWmUKTZW4WAADN1Z60sTLbh7DosCoC07PBoB1gN+CQ4Rto2+dn2OItFTSwj4n3waHXaYNV7zzbcefuFAaSEVOa6bL7aQLs3k9vTeNq/hujnTVOwfqQst3AAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'qBsCfAvn6bI', '/images/films/qBsCfAvn6bI.webp', '/images/films/og/qBsCfAvn6bI.jpg', 1280, 720, 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwAgCdASoQAAkAA4BaJYwCdAEXfsWO/Vw2KAD+nCRaDx/KPgPyA3SsMkGD6c/fo8h6EBht7UsysrsDcjbf20vFbmNw6C8el8Qkyli83OCMp1X39zQdYloqzi3UAWxtCzcnxBzolAAAAA==', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'tlucLNe7aQI', '/images/films/tlucLNe7aQI.webp', '/images/films/og/tlucLNe7aQI.jpg', 1280, 720, 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJbACdADp45e9UjAA/odLBp/TEMQgeJJwPP6CvG2sWgE6PMg4p5v8Aimd72kT3eJzwtIKh/oFk974b9ppEmItCZ28+BNgAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('films', 'xZHzDT7CFSs', '/images/films/xZHzDT7CFSs.webp', '/images/films/og/xZHzDT7CFSs.jpg', 1280, 720, 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgBoZq8KAAPl3KG8u/N9fi+KrFgPcD/qvRRJzyhp51IC9WFZCCNoHk/jN18nw5e/Kc711cndJe0C1DkRgIAYwErzS4AA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('blog', 'bride-and-groom-sushil-indu', '/images/blog/bride-and-groom-sushil-indu.webp', '/images/blog/og/bride-and-groom-sushil-indu.jpg', 1280, 720, 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdAECupVMAAD+v8ZGEt1NA/Dhr6QsP3Owm03fatJP38CfHUV+YsFcdCuh0gm8iwwmEHrmVpPVjAbRpipkAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('blog', 'chaurasi-puja-family-panchamul', '/images/blog/chaurasi-puja-family-panchamul.webp', '/images/blog/og/chaurasi-puja-family-panchamul.jpg', 1280, 720, 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJZgCdADjMRuHZAD2KrsayxTjLKLjX+D03Q27qEZPl7qRhETwpOz+jZY6TrI1CflnBAjb50KHUY15eSmW6n/5tOkWXlr5cbskAA==', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('blog', 'panchebaja-band-arjunchaupari', '/images/blog/panchebaja-band-arjunchaupari.webp', '/images/blog/og/panchebaja-band-arjunchaupari.jpg', 1280, 720, 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgBoZq8KAAPl3KG8u/N9fi+KrFgPcD/qvRRJzyhp51IC9WFZCCNoHk/jN18nw5e/Kc711cndJe0C1DkRgIAYwErzS4AA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('blog', 'pasni-ceremony-walling', '/images/blog/pasni-ceremony-walling.webp', '/images/blog/og/pasni-ceremony-walling.jpg', 1280, 720, 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJbACdADp45e9UjAA/odLBp/TEMQgeJJwPP6CvG2sWgE6PMg4p5v8Aimd72kT3eJzwtIKh/oFk974b9ppEmItCZ28+BNgAAA=', false) on conflict do nothing;
insert into public.media (collection, name, src, og_src, width, height, blur_data_url, in_storage) values ('blog', 'wedding-tika-basanta-bindu-syangja', '/images/blog/wedding-tika-basanta-bindu-syangja.webp', '/images/blog/og/wedding-tika-basanta-bindu-syangja.jpg', 1080, 720, 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQAAsAA4BaJbACdAEPevUBbWgA/ietl0bdFpZN5pRRY8OOdPFwUjAz9MYdH6HmJcE5Itz87lpxfkGQT2WGu8zDq2RcSHp/OeP5ugcY3IJGnVCpZeQ+n1BSIMAhRigAAAA=', false) on conflict do nothing;

insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('2thTrQR3pec', 'basanta-weds-bindu', 'Basanta weds Bindu', 'basanta weds bindu', '', 'weddings', '', '2026-08-20', true, false, true, '{"src":"/images/films/2thTrQR3pec.webp","width":1080,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQAAsAA4BaJbACdAEPevUBbWgA/ietl0bdFpZN5pRRY8OOdPFwUjAz9MYdH6HmJcE5Itz87lpxfkGQT2WGu8zDq2RcSHp/OeP5ugcY3IJGnVCpZeQ+n1BSIMAhRigAAAA=","ogImage":"/images/films/og/2thTrQR3pec.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('TXM4IabFgUk', 'sagar-weds-asmita', 'Sagar weds Asmita', 'SAGAR WEDS ASMITA', '', 'weddings', '', '2026-07-26', false, false, true, '{"src":"/images/films/TXM4IabFgUk.webp","width":1278,"height":720,"blurDataURL":"data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJbACdAEfpwOZUUT4AP7omzFDFhZ0eBVF+SkK33tcJeMuIL0c85Nec6631vyOn2veWXoBqGv7Q/QkyJWmzR3NqTt8AAAA","ogImage":"/images/films/og/TXM4IabFgUk.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('YVc6GEgr9uQ', 'amrit-weds-sabu', 'Amrit weds Sabu', 'AMRIT WEDS SABU', '', 'weddings', '', '2026-07-19', false, false, true, '{"src":"/images/films/YVc6GEgr9uQ.webp","width":1280,"height":512,"blurDataURL":"data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAYAA4BaJbACdADp5orRVoAA/P38YKk/7HoC7CgONb+ES47vKvVDOxSM64o/2N0Rbc3d8aiH9lQMzlePtYgHScyRgW4m4zZS1yjZH7IwnP4P/BPalJqkXwC5n9DcUhBQAAAA","ogImage":"/images/films/og/YVc6GEgr9uQ.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('D8QMlYCuBeA', 'krishna-weds-melina', 'Krishna weds Melina', 'krishna weds Melina', '#fyp  #fypシ #fypyoutube #wedding', 'weddings', '', '2026-07-14', false, false, true, '{"src":"/images/films/D8QMlYCuBeA.webp","width":1080,"height":720,"blurDataURL":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAsAA4BaJbACdAD0oGO5O4BAAP66cMyKcD4qZ8+eVJHoDKd1JcDyquDinfOilX918vTEfkoA3v15CSEnm3kshc2IWdDO23Tq65lp4IQ38Rrl6gKBr43bNtv63uY7xwSnHS1XAAA=","ogImage":"/images/films/og/D8QMlYCuBeA.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('BwOaEbbiVTc', 'kedar-weds-sushma', 'Kedar weds Sushma', 'Kedar weds sushma', '#wedding #singleshoot #love #babbyshoot #sunrise #husbandwife #snapshoot #happy #photoshoo #hedshoot #photoshoo #fyp', 'weddings', '', '2026-06-12', false, false, true, '{"src":"/images/films/BwOaEbbiVTc.webp","width":1068,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAsAA4BaJbACdAC8hnw881gA/u0JLK+sWk3HDqzTz3lFX4TMj127NGLza843ptsYGYFz4WRKvaT8DMMTA8Zrd2bMofOrOd5pMeiDz6344z7qw111f7xxruJP/l2/KjjDgAAA","ogImage":"/images/films/og/BwOaEbbiVTc.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('Rk2D0cbQK34', 'sushil-weds-indu-wedding-highlights', 'Sushil weds Indu: wedding highlights', 'Sushil Wed Indu Highlights', '', 'weddings', '', '2026-05-30', true, false, true, '{"src":"/images/films/Rk2D0cbQK34.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdAECupVMAAD+v8ZGEt1NA/Dhr6QsP3Owm03fatJP38CfHUV+YsFcdCuh0gm8iwwmEHrmVpPVjAbRpipkAAA=","ogImage":"/images/films/og/Rk2D0cbQK34.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('cmmLJ-wB324', 'rapakot-tirsul', 'Rapakot Tirsul', 'RAPAKOT TIRSUL', '', 'culture', '', '2026-05-18', false, true, true, '{"src":"/images/films/cmmLJ-wB324.webp","width":1080,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoQAAsAA4BaJbACdAYv1whvhN+4gAsAAP7miCflrxhK4gOSBdxn0DfoXm9CT46rMYdeCPpUSoPdREoJSYKG6OqOq/XyblvvZqKpIELKsXKcAjL8ZeVW0Gfx48UzkciHEAAAAA==","ogImage":"/images/films/og/cmmLJ-wB324.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('nqMUJ7J7qTg', 'wedding-day-moments', 'Wedding day moments', 'shoot', '', 'weddings', '', '2026-05-13', false, false, true, '{"src":"/images/films/nqMUJ7J7qTg.webp","width":1080,"height":720,"blurDataURL":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAsAA4BaJbACdAEWmUKTZW4WAADN1Z60sTLbh7DosCoC07PBoB1gN+CQ4Rto2+dn2OItFTSwj4n3waHXaYNV7zzbcefuFAaSEVOa6bL7aQLs3k9vTeNq/hujnTVOwfqQst3AAAA=","ogImage":"/images/films/og/nqMUJ7J7qTg.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('3mqD0s53Lvg', 'deepak-weds-laxmi', 'Deepak weds Laxmi', 'deepak weds laxmi', '#sunrise #SUNRISEphotostudio #wedding', 'weddings', '', '2026-05-13', false, false, true, '{"src":"/images/films/3mqD0s53Lvg.webp","width":1278,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAkAA4BaJbACdAYulj5UB0QAAP1QSn+4G+tR8K1pwgMjAXsIpnQy8ib88lltlRpifoYefq6dPLAwCbywJTooJ6c6/3bGe1m97QfiiG/pqj7CuGPn2ymcVRIQAAAA","ogImage":"/images/films/og/3mqD0s53Lvg.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('66Cd8aeqWLQ', 'bratabandha-of-suman-khanal-tirasi', 'Bratabandha of Suman Khanal, Tirasi', 'SUMAN KHANAL TIRASI BARTABANDHA', '', 'ceremonies', 'Tirasi', '2026-05-10', true, false, true, '{"src":"/images/films/66Cd8aeqWLQ.webp","width":1278,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAQCdASoQAAkAA4BaJbACdACb5vJAAPulg808Y1txO03afMeRVav1X5CpYou//9MMNzDNm/bFt+56gmyPiA59ad7zryafS+w4kBuGwmE/I9FJUhFQIHNCQomOWJKWPHD1aMLJ1mw7gAAA","ogImage":"/images/films/og/66Cd8aeqWLQ.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('GTBeZRAIcWQ', 'chaurasi-puja-of-basundhari-rimal-panchamul', 'Chaurasi puja of Basundhari Rimal, Panchamul', 'chaurasi Puja basundhari rimal panchamul', '', 'ceremonies', 'Panchamul', '2026-04-28', false, false, true, '{"src":"/images/films/GTBeZRAIcWQ.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJZgCdADjMRuHZAD2KrsayxTjLKLjX+D03Q27qEZPl7qRhETwpOz+jZY6TrI1CflnBAjb50KHUY15eSmW6n/5tOkWXlr5cbskAA==","ogImage":"/images/films/og/GTBeZRAIcWQ.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('qBsCfAvn6bI', 'asim-weds-srijna-panchamul', 'Asim weds Srijna, Panchamul', 'asim weds srijna panchamul', '', 'weddings', 'Panchamul', '2026-04-28', false, false, true, '{"src":"/images/films/qBsCfAvn6bI.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwAgCdASoQAAkAA4BaJYwCdAEXfsWO/Vw2KAD+nCRaDx/KPgPyA3SsMkGD6c/fo8h6EBht7UsysrsDcjbf20vFbmNw6C8el8Qkyli83OCMp1X39zQdYloqzi3UAWxtCzcnxBzolAAAAA==","ogImage":"/images/films/og/qBsCfAvn6bI.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('tlucLNe7aQI', 'pasni-rice-feeding-ceremony-walling', 'Pasni (rice feeding ceremony), Walling', 'RICE FEEDING CEROMANY WALLING (PASNI)', 'FIRSTRICECEROMANY #PRAYUKTAGHATANG #bibaha #wedding #foryou #love #foryourpage #love #music #photography #ricefeedingceremony #pasni #walling #ajatimlaianakhaunay #photography #sunrise', 'ceremonies', 'Walling', '2026-04-26', true, false, true, '{"src":"/images/films/tlucLNe7aQI.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJbACdADp45e9UjAA/odLBp/TEMQgeJJwPP6CvG2sWgE6PMg4p5v8Aimd72kT3eJzwtIKh/oFk974b9ppEmItCZ28+BNgAAA=","ogImage":"/images/films/og/tlucLNe7aQI.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('QZtJ6EMi_vk', 'bishal-weds-bimala', 'Bishal weds Bimala', 'Bishal weds Bimala', '', 'weddings', '', '2026-04-09', false, false, true, '{"src":"/images/films/QZtJ6EMi_vk.webp","width":480,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoLABAAA4BaJbAC7H8AE13B2A49oAD+5EpECpThsm6wCZOiMwbC68aStxSKEUlt70RfHzfg27Abavb/nC+Bg4+IxwZpe00lUKJJgFJmaPgQApQ7vdtqnuH4TJ/h6ab0AAA=","ogImage":"/images/films/og/QZtJ6EMi_vk.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('2Pn9Ibh7qiI', 'keshav-weds-anita-full-wedding-film', 'Keshav weds Anita: full wedding film', 'keshav weds anita', '', 'weddings', '', '2026-03-19', false, false, true, '{"src":"/images/films/2Pn9Ibh7qiI.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoQAAkAA4BaJQBOgB0kCD8IIAAA/uJ9jfKIkes1v9FB4Phv8SYi62BVo56boUCbWVmWRSkmBcx2wAT377IpUjPHz1W1aej4MFRAvgqNabUVbztsmvV3ie0AAAA=","ogImage":"/images/films/og/2Pn9Ibh7qiI.jpg"}'::jsonb) on conflict do nothing;
insert into public.films (youtube_id, slug, title, youtube_title, youtube_description, category, place, published_at, featured, hidden, curated, thumbnail) values ('xZHzDT7CFSs', 'panchebaja-in-arjunchaupari-singer-bijaya-bishwokarma', 'Panchebaja in Arjunchaupari, singer Bijaya Bishwokarma', 'Panchebaja Syangja Arjunchaupari Singer:Bijaya Bishwokarma', '', 'culture', 'Arjunchaupari', '2019-05-18', false, false, true, '{"src":"/images/films/xZHzDT7CFSs.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgBoZq8KAAPl3KG8u/N9fi+KrFgPcD/qvRRJzyhp51IC9WFZCCNoHk/jN18nw5e/Kc711cndJe0C1DkRgIAYwErzS4AA=","ogImage":"/images/films/og/xZHzDT7CFSs.jpg"}'::jsonb) on conflict do nothing;

insert into public.prints (id, slug, name, name_ne, icon, summary, intro, sections, faqs, inquiry, service_type, featured, highlight, options_heading, options, mockup, preview_film_ids, sort_order) values ('cec3f2c1-10b1-40c5-8209-54169d59502e', 'premium-albums', 'Premium wedding albums', 'प्रिमियम एल्बम', 'BookHeart', 'Designed albums with thick pages and a finished cover, made from your wedding or ceremony photos to last for generations.', array['An album is how most families actually look at their wedding photos: years later, on the sofa, with the relatives who weren''t there. We choose and arrange your best photos into a designed layout that follows the day in order, and have it bound as a premium album.', 'Albums work for pasni, bratabandha and pre-wedding shoots too, often as a smaller book.']::text[], '[{"heading":"How we make your album","items":["You pick your favourite photos, or leave the choice to us","We design the layout, spread by spread, in the order of the day","You check the design and ask for changes","We print and bind it, and call you when it''s ready"]},{"heading":"Photos from another photographer?","body":"Bring them on a pen drive and ask us: we can design an album from photos you already have."}]'::jsonb, '[{"question":"How much does an album cost?","answer":"It depends on the size, the number of pages and the cover. Tell us what you have in mind and we''ll send a quote."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to ask about a premium photo album.', 'Photo album design and printing', true, 'Designed layouts, thick pages', 'Things to decide', '[{"label":"Size and shape","detail":"Landscape or square; bigger albums suit wedding spreads, smaller ones make good gifts for parents"},{"label":"Number of pages","detail":"Depends on how many photos you want in; we''ll suggest a count from your selection"},{"label":"Cover","detail":"A photo cover, or a plain cover with your names"},{"label":"Copies","detail":"A second, smaller copy for parents or in-laws is a popular gift"}]'::jsonb, 'album', array['2thTrQR3pec', 'Rk2D0cbQK34']::text[], 10) on conflict do nothing;
insert into public.prints (id, slug, name, name_ne, icon, summary, intro, sections, faqs, inquiry, service_type, featured, highlight, options_heading, options, mockup, preview_film_ids, sort_order) values ('6a9032d1-025f-4fca-b338-bc3c44143d12', 'photo-frames', 'Photo frames', 'फोटो फ्रेम', 'Frame', 'Your photo printed and framed, ready for the wall or a table: wedding portraits, family groups and collages in standard sizes.', array['A framed photo is the one you see every day. We print your photo and frame it in the studio, from a small frame for a table or a gift to a large portrait for the living room wall.']::text[], '[{"heading":"Good for","items":["The main wedding portrait","A family group photo from a ceremony or a festival","A collage of pasni or birthday photos","A gift for parents or in-laws","A portrait of a late family member for the home"]},{"heading":"Printing a photo from your phone","body":"Send it on WhatsApp as a document, not as a photo: WhatsApp shrinks photos, which shows up in a big print. For a large frame, send the original from the camera if you have it."}]'::jsonb, '[{"question":"Do you have other sizes?","answer":"Ask us. Tell us the size and where the frame will hang and we''ll tell you what we can make."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to frame a photo. Size: ', 'Photo framing', true, '5×7 to 20×30 in', 'Common sizes', '[{"label":"5×7 in","detail":"Table frames and gifts"},{"label":"8×10 in","detail":"Desks, shelves and small walls"},{"label":"8×12 in","detail":"The same shape as a camera photo, so nothing is cropped"},{"label":"12×18 in","detail":"Wall portraits for bedrooms and hallways"},{"label":"16×24 in","detail":"The main wedding portrait in a living room"},{"label":"20×30 in","detail":"A large feature wall"}]'::jsonb, 'frame', array['tlucLNe7aQI']::text[], 20) on conflict do nothing;
insert into public.prints (id, slug, name, name_ne, icon, summary, intro, sections, faqs, inquiry, service_type, featured, highlight, options_heading, options, mockup, preview_film_ids, sort_order) values ('bab6a327-1583-4b50-8ae0-2eb060b18f3d', 'canvas-prints', 'Canvas prints', 'क्यानभास प्रिन्ट', 'Image', 'Photos printed on canvas and stretched over a frame: no glass and no glare, with a painting-like finish for large wall pieces.', array['Canvas suits a big, simple photo: a couple portrait, a baby''s face, a landscape from home. With no glass there''s no reflection, so it reads from anywhere in the room.']::text[], '[{"heading":"Canvas or a framed print?","items":["Canvas: no glass, no glare and a soft texture. Best for one or two people and bold, simple photos.","Framed print behind glass: sharper fine detail. Better for big family groups where every face matters."]},{"heading":"Which photos work best","body":"Choose a photo that''s sharp and well lit, with the faces reasonably large in the frame. A small face in a wide group photo doesn''t get better when it''s printed big."}]'::jsonb, '[{"question":"Can you make a canvas from an old photo?","answer":"Bring it in and we''ll look at it together. Whether it prints well at a large size depends on the original."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to ask about a canvas print. Size: ', 'Canvas printing', true, 'No glass, no glare', 'Common sizes', '[{"label":"12×18 in","detail":"A single portrait in a bedroom or hallway"},{"label":"16×24 in","detail":"Above a sofa or a bed"},{"label":"20×30 in","detail":"The main piece on a large wall"}]'::jsonb, 'canvas', array['GTBeZRAIcWQ']::text[], 30) on conflict do nothing;
insert into public.prints (id, slug, name, name_ne, icon, summary, intro, sections, faqs, inquiry, service_type, featured, highlight, options_heading, options, mockup, preview_film_ids, sort_order) values ('49616578-03f9-4928-aea8-b3028cfea43d', 'photo-prints', 'Photo prints', 'फोटो प्रिन्ट', 'Printer', 'Prints from your camera or phone in standard sizes, from 4×6 in keepsakes to 12×18 in enlargements.', array['Most photos now live on phones and never get printed. Send us the ones worth keeping and we''ll print them in the size you need, for an album at home, a school project or a gift.']::text[], '[{"heading":"Sending us your photos","items":["WhatsApp: send them as a document, not as a photo, so they aren''t compressed","Pen drive or memory card: bring it to the studio","Tell us the size and how many copies of each"]},{"heading":"Which size fits your photo","body":"Camera photos are 3:2, so 4×6, 8×12 and 12×18 print them whole. Phone photos are usually 4:3, which fits 6×8. Other sizes crop a little from the edges; we''ll check before printing."}]'::jsonb, '[{"question":"Can you print from Facebook or Instagram?","answer":"We can, but those copies are small and compressed, so they only print well at small sizes. Ask the person who took the photo for the original if you can."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like some photos printed.', 'Photo printing', false, '4×6 to 12×18 in', 'Sizes', '[{"label":"4×6 in","detail":"The classic print for albums and envelopes"},{"label":"5×7 in","detail":"Table frames and cards"},{"label":"6×8 in","detail":"Fits phone photos (4:3) without cropping"},{"label":"8×10 in","detail":"Frames and certificates; crops a camera photo slightly"},{"label":"8×12 in","detail":"Fits camera photos (3:2) without cropping"},{"label":"12×18 in","detail":"Enlargements and posters"}]'::jsonb, 'loose-prints', array['xZHzDT7CFSs', 'nqMUJ7J7qTg', 'Rk2D0cbQK34']::text[], 40) on conflict do nothing;
insert into public.prints (id, slug, name, name_ne, icon, summary, intro, sections, faqs, inquiry, service_type, featured, highlight, options_heading, options, mockup, preview_film_ids, sort_order) values ('c7d6dbb1-f304-45f0-b0c1-31a868660127', 'photo-books', 'Photo books', 'फोटो बुक', 'BookImage', 'Smaller printed books for a pre-wedding shoot, a pasni or a family trip: a lighter keepsake than a full album, and an easy gift.', array['Not every occasion needs a full wedding album. A photo book holds the best photos of a pre-wedding shoot, a baby''s pasni or a family trip in something small enough to post to relatives abroad.']::text[], '[{"heading":"How to order","items":["Send or bring your photos","Tell us the occasion and how many copies","We lay out the pages and print"]}]'::jsonb, '[{"question":"What''s the difference from a premium album?","answer":"A premium album is larger, with thick pages and a finished cover, made to last as the family''s wedding record. A photo book is smaller and lighter: a keepsake or a gift."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to ask about a photo book.', 'Photo book printing', false, 'Small, giftable keepsakes', 'Good for', '[{"label":"Pre-wedding shoots","detail":"Pages from your couple shoot, often shown at the wedding"},{"label":"Pasni and first birthdays","detail":"A baby''s first year in one small book"},{"label":"Family gatherings","detail":"Dashain, Tihar and the visits of relatives from abroad"},{"label":"Gifts","detail":"Extra copies for grandparents and relatives"}]'::jsonb, 'book', array['QZtJ6EMi_vk']::text[], 50) on conflict do nothing;

insert into public.services (slug, name, name_ne, short_name, icon, summary, intro, sections, faqs, inquiry, service_type, featured, cover_film_id, film_category, related_print_ids, sort_order) values ('wedding-photography', 'Wedding photography', 'विवाह फोटोग्राफी', 'Wedding photos', 'Heart', 'Every ritual of a Nepali wedding photographed in order, from the janti and swayambar to sindur, kanyadan and the bidaai.', array['A Nepali wedding runs across a long day, often two, and its most important rituals happen once and quickly. We photograph the whole day and the family around it, so your photos tell the story in the order it happened: getting ready, the janti arriving, the swayambar, the rituals at the mandap and the bidaai.', 'We cover weddings at homes, party palaces and temples across Syangja. The films on this page are from weddings we''ve shot recently.']::text[], '[{"heading":"Moments we photograph","items":["Getting ready: the bride''s dressing and mehendi, the groom''s family preparing","The janti arriving with panchebaja, and the welcome at the bride''s home","Swayambar and the exchange of garlands","Kanyadan, sindur and pote, and the seven steps around the fire","Tika and blessings from elders, and group photos of both families","The bidaai, and the welcome at the groom''s home","Reception, dancing and the guests"]},{"heading":"What you can take home","items":["Edited photos of the whole day","A premium album designed from your photos","Framed and canvas prints of your favourite portraits","A full wedding film and a highlight video, if you add video"]},{"heading":"Help us plan your day","body":"Send us the schedule (with the sait times for each ritual) about a week before, and name one relative who knows both families to help gather people for group photos. If your family or community has a ritual we might not expect, tell us so we''re in the right place when it happens."}]'::jsonb, '[{"question":"How early should we book?","answer":"As soon as your date is fixed. Wedding-season dates fill first. Message us your date and venue and we''ll tell you whether we''re free."},{"question":"How much does wedding photography cost?","answer":"It depends on the hours, how many photographers and videographers you need, and whether you add a film, an album or frames. Send us your date, venue and what you''d like, and we''ll send you a quote."},{"question":"Can you cover both the bride''s and the groom''s side?","answer":"Tell us the venues and timings on each side and we''ll plan the coverage with you."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to ask about wedding photography. Our date is: ', 'Wedding photography', true, '2thTrQR3pec', 'weddings', array['cec3f2c1-10b1-40c5-8209-54169d59502e', '6a9032d1-025f-4fca-b338-bc3c44143d12', 'bab6a327-1583-4b50-8ae0-2eb060b18f3d']::uuid[], 10) on conflict do nothing;
insert into public.services (slug, name, name_ne, short_name, icon, summary, intro, sections, faqs, inquiry, service_type, featured, cover_film_id, film_category, related_print_ids, sort_order) values ('wedding-films', 'Wedding films', 'विवाह भिडियो', 'Wedding films', 'Clapperboard', 'A full-length film of your wedding and a short highlight to share, edited with music and titled with your names.', array['Alongside the photos, we film the wedding and edit it into something the whole family can watch together again: a full-length film that follows the day in order, and a highlight video of a few minutes to share.', 'Our full wedding films are long enough to include every ritual: Keshav and Anita''s runs well over two hours. Relatives in Nepal and abroad watch them on our YouTube channel.']::text[], '[{"heading":"What a wedding film can include","items":["The full film, following every ritual of the day in order","A highlight video of a few minutes, cut to music","A title design with your names and wedding date","Short clips sized for Facebook and phone screens"]},{"heading":"Watching and sharing","body":"With your permission we publish the film on our YouTube channel, so family anywhere can watch it the same way. Tell us if you''d rather keep it off YouTube, and ask us for the video files to keep."}]'::jsonb, '[{"question":"Can we see your films first?","answer":"Yes. Every film we publish is on our Films page and on our YouTube channel."},{"question":"Can we book only a highlight video?","answer":"Tell us what you need, whether that''s the full film, a highlight or both, and we''ll quote for it."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to ask about a wedding film. Our date is: ', 'Wedding videography', true, 'Rk2D0cbQK34', 'weddings', array['cec3f2c1-10b1-40c5-8209-54169d59502e']::uuid[], 20) on conflict do nothing;
insert into public.services (slug, name, name_ne, short_name, icon, summary, intro, sections, faqs, inquiry, service_type, featured, cover_film_id, film_category, related_print_ids, sort_order) values ('pre-wedding-shoots', 'Pre-wedding and couple shoots', 'प्रि-वेडिङ सुट', 'Pre-wedding shoots', 'Flower2', 'A relaxed shoot for the two of you before the wedding, outdoors or in the studio, for invitations, save-the-dates and your walls.', array['A pre-wedding shoot is the calm part of the wedding: an hour or two for just the two of you, without a schedule or a crowd. It''s also practice: by the wedding day you''re used to the camera.', 'The photos go on your invitation cards and save-the-date posts, and the best one often ends up framed at home.']::text[], '[{"heading":"Where to shoot","items":["A place that means something to you: your village, a temple, the fields or hills nearby","Our studio, for clean portraits in any weather","Both: a few studio portraits, then outside while the light is soft"]},{"heading":"What to wear","body":"Bring two outfits if you can: something traditional (daura suruwal, sari or gunyu cholo) and something you''d wear on a day out. Plain colours photograph better than busy prints."},{"heading":"Where the photos go","items":["Wedding invitation cards","Save-the-date posts","A framed print or canvas for home","A small photo book"]}]'::jsonb, '[{"question":"When should we do it?","answer":"A few weeks before the wedding, so there''s time to use the photos on your invitations."}]'::jsonb, 'Hello Sunrise Photo Studio, we''d like to ask about a pre-wedding shoot.', 'Engagement photography', false, null, null, array['c7d6dbb1-f304-45f0-b0c1-31a868660127', 'bab6a327-1583-4b50-8ae0-2eb060b18f3d', '6a9032d1-025f-4fca-b338-bc3c44143d12']::uuid[], 30) on conflict do nothing;
insert into public.services (slug, name, name_ne, short_name, icon, summary, intro, sections, faqs, inquiry, service_type, featured, cover_film_id, film_category, related_print_ids, sort_order) values ('family-ceremonies', 'Pasni, bratabandha and family ceremonies', 'पास्नी, ब्रतबन्ध र पारिवारिक समारोह', 'Pasni and bratabandha', 'Flame', 'Pasni, bratabandha, chaurasi puja and other family ceremonies, photographed and filmed with every ritual in order.', array['Family ceremonies are smaller than a wedding but just as important, and many of them happen once in a lifetime. We photograph and film them the same way: every ritual in order, and every part of the family in the pictures.', 'Recent ceremonies we''ve filmed include a pasni in Walling, a bratabandha in Tirasi and a chaurasi puja in Panchamul.']::text[], '[{"heading":"Pasni (rice feeding)","body":"A baby''s first taste of rice, usually in the fifth or sixth month. We photograph the baby being dressed, the first feeding by the family, tika and blessings from the elders, and the moment the baby picks from the tray of objects, the photo every family wants."},{"heading":"Bratabandha","body":"The coming-of-age ceremony when a boy receives the sacred thread (janai). The shaving of the head, the saffron robes, the teaching from the guru, the round of bhiksha from relatives and the moment his mama brings him back all make strong photos, and they happen fast."},{"heading":"Chaurasi puja and elders'' celebrations","body":"Chaurasi puja marks an elder reaching 84, about a thousand full moons. The whole extended family comes together for it, so we make sure every branch of the family gets its group photo with them."},{"heading":"Birthdays, anniversaries and pujas","body":"Smaller gatherings too: a first birthday, a wedding anniversary, a house puja. Tell us what''s planned and for how long."}]'::jsonb, '[{"question":"How much does it cost?","answer":"It depends on the length of the ceremony and whether you want photos, a film or both. Send us the date, the place and what''s planned, and we''ll send a quote."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to ask about photos for a family ceremony (pasni / bratabandha / puja). The date is: ', 'Event photography', true, 'tlucLNe7aQI', 'ceremonies', array['6a9032d1-025f-4fca-b338-bc3c44143d12', 'c7d6dbb1-f304-45f0-b0c1-31a868660127', '49616578-03f9-4928-aea8-b3028cfea43d']::uuid[], 40) on conflict do nothing;
insert into public.services (slug, name, name_ne, short_name, icon, summary, intro, sections, faqs, inquiry, service_type, featured, cover_film_id, film_category, related_print_ids, sort_order) values ('studio-portraits', 'Studio portraits and family photos', 'स्टुडियो पोर्ट्रेट र पारिवारिक फोटो', 'Portraits', 'Users', 'Portraits in our studio in Arjunchaupari: families, couples, children, graduates and profile photos, printed and ready to frame.', array['Some photos are worth making on purpose: the whole family together while relatives are home for Dashain or Tihar, a child''s first birthday, a graduate in their gown, a portrait of your parents.', 'Come to the studio and we''ll take care of the light, the background and the posing, then print your favourites to frame.']::text[], '[{"heading":"Who comes in","items":["Families, especially when relatives are visiting from abroad","Couples and newly-weds","Babies and children","Graduates and students","Expecting mothers","Profile photos for CVs and applications"]},{"heading":"Take it home","body":"Most portraits end up on a wall. We print and frame in the studio, from a small table frame to a large canvas."}]'::jsonb, '[{"question":"Do we need an appointment?","answer":"It''s best to call or message before you come, especially for a large family group, so we''re ready for you."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to book a studio portrait session.', 'Portrait photography', true, 'GTBeZRAIcWQ', null, array['6a9032d1-025f-4fca-b338-bc3c44143d12', 'bab6a327-1583-4b50-8ae0-2eb060b18f3d', '49616578-03f9-4928-aea8-b3028cfea43d']::uuid[], 50) on conflict do nothing;
insert into public.services (slug, name, name_ne, short_name, icon, summary, intro, sections, faqs, inquiry, service_type, featured, cover_film_id, film_category, related_print_ids, sort_order) values ('events-and-culture', 'Events, programmes and cultural shows', 'कार्यक्रम तथा सांस्कृतिक प्रस्तुति', 'Events and culture', 'PartyPopper', 'School and community programmes, engagements, receptions, panchebaja and cultural performances, photographed and filmed on location.', array['Beyond family occasions, we photograph and film the events that bring a village or an organisation together, and the music that goes with them. Our panchebaja film from Arjunchaupari is one example.']::text[], '[{"heading":"Events we cover","items":["School programmes and prize days","Community, cooperative and organisation meetings","Engagements and receptions","Panchebaja, naumati baja and local singers","Cultural programmes and performances"]},{"heading":"What you receive","items":["Edited photos of the event","An event film or a short highlight","Clips for your organisation''s Facebook page"]}]'::jsonb, '[{"question":"Can you cover events outside Arjunchaupari?","answer":"We film across Syangja. Tell us the place and date and we''ll let you know."}]'::jsonb, 'Hello Sunrise Photo Studio, I''d like to ask about coverage for an event. The date and place are: ', 'Event photography', false, 'xZHzDT7CFSs', 'culture', array['49616578-03f9-4928-aea8-b3028cfea43d']::uuid[], 60) on conflict do nothing;
insert into public.services (slug, name, name_ne, short_name, icon, summary, intro, sections, faqs, inquiry, service_type, featured, cover_film_id, film_category, related_print_ids, sort_order) values ('passport-photos', 'Passport, visa and ID photos', 'पासपोर्ट साइज फोटो', 'Passport photos', 'IdCard', 'Passport-size and ID photos taken and printed in the studio, the same day. Walk-in friendly.', array['Need photos for a citizenship certificate, a licence, a visa, or a job or school application? Come to the studio: we take the photo, set it to the size the form asks for, and print it the same day.']::text[], '[{"heading":"Bring the requirement with you","body":"Sizes and rules differ between forms and countries, and embassies change them. Bring the exact requirement (the page from the form or the embassy''s website) and we''ll match it: size, background colour and how much of the face should fill the frame."},{"heading":"What to wear","items":["Clothes that stand out from a white or light background","Hair away from the face; many forms ask for both ears visible","No glasses, unless the form allows them"]}]'::jsonb, '[{"question":"Can I get a digital copy for an online form?","answer":"Ask for the digital file when you come in, and tell us the size in pixels or kilobytes the website asks for."}]'::jsonb, 'Hello Sunrise Photo Studio, I need passport / ID photos.', 'Passport photo service', false, null, null, array['49616578-03f9-4928-aea8-b3028cfea43d']::uuid[], 70) on conflict do nothing;

insert into public.posts (slug, title, summary, body, status, published_at, updated_on, author, tags, language, featured, cover, cover_alt, cover_credit, cover_credit_url, cover_license, cover_license_url, reading_minutes, headings) values ('panchebaja-wedding-music', 'Panchebaja: the sound of a Nepali wedding, on film', 'What the panchebaja is, the instruments in it, and why we film the band as carefully as the couple.', 'If there''s one sound that tells a whole village a wedding is on, it''s the panchebaja. The band leads the janti, plays through the rituals and sends the bride off at the bidaai. In a wedding film it does more than fill the soundtrack: it tells you where you are.

## Five instruments, and sometimes more

Panchebaja (पञ्चे बाजा) means "five instruments". The usual five are:

- **Sanai (shehnai):** a double-reed wind instrument that carries the melody.
- **Damaha:** a large kettle drum.
- **Tyamko:** a small kettle drum, played with two sticks for the quick rhythms.
- **Dholaki:** a two-headed barrel drum.
- **Jhyali:** a pair of cymbals.

Many bands add the **narsinga**, a long curved horn whose sound carries across the hills, and the **karnal**, a straight horn. A band with nine instruments is called a **naumati baja**. The music has traditionally been played by musicians of the Damai community, often passed down within families.

## Why we film the band

- **It sets the scene.** A few seconds of the band marching up the path is the fastest way to show that a film is about a wedding in the hills, not in a city hall.
- **It carries the edit.** Highlight videos cut to the band''s rhythm feel like the day did.
- **Elders notice.** For many families, the band is part of what makes a wedding proper, and relatives watching from abroad hear home in it.
- **The bands deserve it.** The music is a living tradition, and good recordings of it are worth keeping.

## Getting good sound

The camera''s own microphone struggles with a band in the open air: the drums overpower the sanai, and the wind takes the rest. Recording close to the band as well keeps the melody in the film. Our film of a panchebaja in Arjunchaupari, with singer Bijaya Bishwokarma, is on our [films page](/films?category=culture).

## If you''re booking a band

Tell your photographer when the band is due to arrive and what route the janti will take. The best shots happen on the way, where the procession passes fields, fences and neighbours watching from their doorways, not at the gate.

For more on the instruments and their history, the Wikipedia article on [Panche baja](https://en.wikipedia.org/wiki/Panche_baja) is a good starting point. To have your wedding, band and all, filmed, see our [wedding films](/services/wedding-films).
', 'published', '2026-09-27', null, '', array['Culture', 'Weddings']::text[], 'en', false, '{"src":"/images/blog/panchebaja-band-arjunchaupari.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAkAA4BaJQBOgBoZq8KAAPl3KG8u/N9fi+KrFgPcD/qvRRJzyhp51IC9WFZCCNoHk/jN18nw5e/Kc711cndJe0C1DkRgIAYwErzS4AA=","ogImage":"/images/blog/og/panchebaja-band-arjunchaupari.jpg"}'::jsonb, 'A panchebaja band plays drums and horns outdoors in Arjunchaupari while a man in a suit dances in front of them', 'Sunrise Photo Studio, from the film Panchebaja in Arjunchaupari', 'https://www.youtube.com/watch?v=xZHzDT7CFSs', '', '', 2, '[{"id":"five-instruments-and-sometimes-more","text":"Five instruments, and sometimes more","depth":2},{"id":"why-we-film-the-band","text":"Why we film the band","depth":2},{"id":"getting-good-sound","text":"Getting good sound","depth":2},{"id":"if-youre-booking-a-band","text":"If you''re booking a band","depth":2}]'::jsonb) on conflict do nothing;
insert into public.posts (slug, title, summary, body, status, published_at, updated_on, author, tags, language, featured, cover, cover_alt, cover_credit, cover_credit_url, cover_license, cover_license_url, reading_minutes, headings) values ('pasni-and-bratabandha-photos', 'Pasni and bratabandha: the photos worth planning for', 'The moments that make a rice feeding ceremony and a bratabandha, when they happen, and how to plan the day so the photographer catches them.', 'A pasni and a bratabandha each happen once in a child''s life. They''re shorter than a wedding, but they have their own rituals, in their own order, and the important ones are quick. Here''s what to plan for.

## Pasni: the first rice

The pasni (annaprashan) is a baby''s first taste of rice, usually held in the fifth month for a girl and the sixth for a boy, on a day the family priest picks. Customs differ between families and communities, but these are the moments families most often ask for:

- **Dressing the baby.** Often in new clothes and jewellery given by the maternal family.
- **The first feeding.** Usually rice pudding (kheer), fed by an elder of the family, and then by each relative in turn.
- **Tika and blessings** from grandparents and elders.
- **Choosing from the tray.** Many families place objects in front of the baby (a book, a pen, money, clay, jewellery) and watch which one the baby reaches for. It''s the moment everyone crowds around, so tell the photographer before it starts.
- **Family groups:** the baby with parents, with grandparents on both sides, and with the maternal family.

### Plan around the baby

The baby decides how the day goes. Try to time the ceremony after a nap and a feed, keep the room from getting too hot and crowded, and don''t worry about tears: some of the best pasni photos are of a baby who clearly did not want the rice.

## Bratabandha: the sacred thread

In a bratabandha, a boy receives the sacred thread (janai) and is initiated into adulthood in the family''s tradition, usually somewhere between the ages of seven and thirteen. It''s a long day, and much of it happens early in the morning. The moments that make the strongest photos:

- **The shaving of the head,** leaving the tuft of hair (tupi). Often at dawn, so the photographer needs to arrive early.
- **The saffron robes** and the walking stick of an ascetic.
- **Receiving the janai** and the teaching from the guru, often whispered into the boy''s ear under a cloth.
- **The bhiksha round,** when he asks his relatives for alms, starting with his mother.
- **Leaving and coming back.** In many families, the boy sets off as if to leave home for a life of study, and his mama (maternal uncle) brings him back. Families love this moment and it''s easy to miss.
- **Family groups** with the boy in his robes, especially with his maternal family.

## For both ceremonies

- **Share the timings from the priest** a few days before, including anything that happens before sunrise.
- **Keep one relative free** to gather people for group photos. The elders are the ones you''ll most want pictures with later.
- **Leave room around the ritual.** Relatives with phones tend to form a wall in front of the child at the key moments. Ask them to give the photographer a gap for those few seconds.

## Afterwards

Pasni and bratabandha photos make good small [photo books](/prints/photo-books) to send to relatives abroad, and a single framed portrait of the child from the day often stays on the wall for years. You can see ceremonies we''ve filmed, including this pasni in Walling and a bratabandha in Tirasi, on our [films page](/films?category=ceremonies).

Planning one? Read about our [family ceremony coverage](/services/family-ceremonies) or [send us the date](/contact).
', 'published', '2026-09-27', null, '', array['Ceremonies', 'Planning']::text[], 'en', false, '{"src":"/images/blog/pasni-ceremony-walling.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkAA4BaJbACdADp45e9UjAA/odLBp/TEMQgeJJwPP6CvG2sWgE6PMg4p5v8Aimd72kT3eJzwtIKh/oFk974b9ppEmItCZ28+BNgAAA=","ogImage":"/images/blog/og/pasni-ceremony-walling.jpg"}'::jsonb, 'A smiling woman in red with tika on her forehead holds a baby during a pasni ceremony in Walling', 'Sunrise Photo Studio, from the film Pasni (rice feeding ceremony), Walling', 'https://www.youtube.com/watch?v=tlucLNe7aQI', '', '', 3, '[{"id":"pasni-the-first-rice","text":"Pasni: the first rice","depth":2},{"id":"plan-around-the-baby","text":"Plan around the baby","depth":3},{"id":"bratabandha-the-sacred-thread","text":"Bratabandha: the sacred thread","depth":2},{"id":"for-both-ceremonies","text":"For both ceremonies","depth":2},{"id":"afterwards","text":"Afterwards","depth":2}]'::jsonb) on conflict do nothing;
insert into public.posts (slug, title, summary, body, status, published_at, updated_on, author, tags, language, featured, cover, cover_alt, cover_credit, cover_credit_url, cover_license, cover_license_url, reading_minutes, headings) values ('photo-print-and-frame-sizes', 'Photo print and frame sizes: which size for which photo', 'Why some sizes crop your photo and others don''t, how big a phone photo can be printed, and which frame size suits which wall.', 'Print sizes look like a random list of numbers: 4×6, 5×7, 8×10, 8×12, 12×18. They aren''t random, and knowing why saves you from a print with someone''s head cut off at the edge. Sizes here are in inches, as they''re sold in Nepal.

## Your photo has a shape

Every photo has an aspect ratio: its width compared to its height.

- **Camera photos are 3:2.** DSLR and mirrorless cameras make photos in this shape.
- **Phone photos are usually 4:3.** A little squarer than a camera photo.

A print whose shape matches the photo shows all of it. A print with a different shape has to cut something off the edges.

| Size (in) | Shape | Fits a camera photo? | Fits a phone photo? |
| --- | --- | --- | --- |
| 4×6 | 3:2 | Yes, whole | Crops a little |
| 5×7 | 7:5 | Crops a little | Crops a little |
| 6×8 | 4:3 | Crops a little | Yes, whole |
| 8×10 | 5:4 | Crops more | Crops a little |
| 8×12 | 3:2 | Yes, whole | Crops a little |
| 12×18 | 3:2 | Yes, whole | Crops a little |

A little cropping is often fine, but in a tight family group the person at each end is the one who loses out. Tell us who must stay in the picture and we''ll check before printing.

## How big can a photo be printed?

A sharp print needs enough pixels. A useful rule: aim for about 200 to 300 pixels for every inch of print. Larger prints hung on a wall are seen from further away, so they can get by with less.

- A **4×6** print needs about 1200 × 1800 pixels for full quality.
- A modern phone photo (12 megapixels, 4032 × 3024) prints well up to about **12×16**.
- For **16×24 and larger**, use the original from a camera if you can.

The catch is how the photo reaches us. **WhatsApp shrinks photos** sent the normal way, and Facebook and Instagram do the same. Send the photo as a document on WhatsApp, or bring the original on a pen drive, and it arrives at full size.

## Which size for which place

| Where it goes | Size to consider |
| --- | --- |
| A table, a shelf, a gift | 5×7 or 6×8 |
| A desk or a small wall | 8×10 or 8×12 |
| A bedroom or hallway wall | 12×18 |
| Above a sofa or a bed | 16×24 |
| The main wall of a living room | 20×30 |

A useful test: cut a sheet of newspaper to the size and tape it to the wall for a day. Most people find they wanted one size bigger.

## Framed print or canvas?

A framed print behind glass keeps fine detail sharp, which matters in a big family group where every face should be recognisable. A canvas has no glass, so there''s no glare from windows or lights, and its texture suits a single bold portrait. There''s more on each on our [photo frames](/prints/photo-frames) and [canvas prints](/prints/canvas-prints) pages.

## Old photos

Old family prints can be copied and printed again, but a small, faded print won''t become sharp when it''s enlarged. For a portrait of a late family member, bring the best original you have and we''ll suggest the size it will hold up at.

Ready to print? Send your photos to us on [WhatsApp](/contact) with the size you want.
', 'published', '2026-09-27', null, '', array['Prints', 'Guides']::text[], 'en', false, '{"src":"/images/blog/chaurasi-puja-family-panchamul.webp","width":1280,"height":720,"blurDataURL":"data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJZgCdADjMRuHZAD2KrsayxTjLKLjX+D03Q27qEZPl7qRhETwpOz+jZY6TrI1CflnBAjb50KHUY15eSmW6n/5tOkWXlr5cbskAA==","ogImage":"/images/blog/og/chaurasi-puja-family-panchamul.jpg"}'::jsonb, 'An elderly woman in a white shawl sits beside a younger relative holding a small child, in a garden during a chaurasi puja', 'Sunrise Photo Studio, from the film Chaurasi puja of Basundhari Rimal, Panchamul', 'https://www.youtube.com/watch?v=GTBeZRAIcWQ', '', '', 3, '[{"id":"your-photo-has-a-shape","text":"Your photo has a shape","depth":2},{"id":"how-big-can-a-photo-be-printed","text":"How big can a photo be printed?","depth":2},{"id":"which-size-for-which-place","text":"Which size for which place","depth":2},{"id":"framed-print-or-canvas","text":"Framed print or canvas?","depth":2},{"id":"old-photos","text":"Old photos","depth":2}]'::jsonb) on conflict do nothing;
insert into public.posts (slug, title, summary, body, status, published_at, updated_on, author, tags, language, featured, cover, cover_alt, cover_credit, cover_credit_url, cover_license, cover_license_url, reading_minutes, headings) values ('wedding-photo-and-video-checklist', 'Wedding photos and video in Nepal: a planning checklist', 'When to book, what to decide early, the schedule to share and the group photos to plan, so nothing important happens off camera.', 'A Nepali wedding moves fast. The janti arrives, the swayambar happens, the rituals at the mandap run into the night, and by the next morning it''s the bidaai. The photos and the film are what you''ll keep, so a little planning goes a long way. This checklist is the order we''d do it in.

## 1. Book as soon as the date is fixed

Auspicious dates in the wedding season are shared by many families, so photographers and videographers get booked early. When you message a studio, send:

- The date (and the second day, if the wedding runs over two)
- The venues on both sides: home, party palace or temple
- Whether you want photos, a film, or both
- Roughly how many guests

## 2. Decide what you want to keep

It changes who comes on the day. A film needs a videographer as well as a photographer, and a long ceremony on both sides may need more than one of each. Think about:

- **Edited photos** of the whole day
- **A full-length film** for the family, and **a short highlight** to share
- **An album**: most families still look at their wedding this way, years later (see [premium albums](/prints/premium-albums))
- **Frames** for the main portrait and a family group (see [photo frames](/prints/photo-frames))

## 3. Share the schedule a week before

The single most useful thing you can give your photographer is the schedule, with the sait times from your priest. A simple table is enough:

| What | When | Where | Who must be there |
| --- | --- | --- | --- |
| Janti leaves / arrives | | | Groom, family, panchebaja |
| Swayambar | | | Bride, groom, both families |
| Kanyadan | | | Bride''s parents |
| Sindur and pote | | | Bride, groom |
| Bidaai | | | Bride''s family |

If your family or community has a ritual we might not expect, add it. Being in the right place for thirty seconds is often the whole job.

## 4. Name one family coordinator

Pick a relative who knows both families and isn''t busy with a ritual. They find the maternal uncle for the group photo, tell us who the important elders are, and keep the schedule moving. Without one, the photographer ends up asking strangers who everyone is.

## 5. Plan the group photos

Group photos are the ones people look for later, and the easiest to forget. Write down the groups you want, for example:

- Bride with her parents and siblings
- The bride''s maternal side (mamaghar)
- The groom''s family, then both families together
- Grandparents with the couple
- Friends

The best time is when everyone is already gathered: straight after the swayambar, or before the meal is served.

## 6. Think about light

Much of a Nepali wedding happens at night, under strong coloured lights in a tent or a hall. That''s part of the atmosphere, but it changes skin tones. If you can, keep some white light near the mandap, and plan the couple portraits for the morning or late afternoon, when the daylight is soft.

## 7. On the day

- Ask relatives with phones not to stand between the couple and the camera during the sindur and the kanyadan. These are the moments everyone wants, and they''re over in seconds.
- Keep the ritual items (garlands, the tika plate, the pote) ready where the photographer can see them.
- Eat. It''s a long day for the couple, too.

## 8. After the wedding

Choose the photos for your album while you still remember who everyone is, order frames for the main portrait, and share the film link with relatives who couldn''t come. The [films we''ve made](/films?category=weddings) are on our YouTube channel, where family abroad watch them.

If you''re planning a wedding in Syangja, [send us your date](/contact) and we''ll tell you if we''re free.
', 'published', '2026-09-27', null, '', array['Weddings', 'Planning']::text[], 'en', true, '{"src":"/images/blog/wedding-tika-basanta-bindu-syangja.webp","width":1080,"height":720,"blurDataURL":"data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQAAsAA4BaJbACdAEPevUBbWgA/ietl0bdFpZN5pRRY8OOdPFwUjAz9MYdH6HmJcE5Itz87lpxfkGQT2WGu8zDq2RcSHp/OeP5ugcY3IJGnVCpZeQ+n1BSIMAhRigAAAA=","ogImage":"/images/blog/og/wedding-tika-basanta-bindu-syangja.jpg"}'::jsonb, 'Relatives in red and pink welcome the groom in his dhaka topi and garland at the bride''s home in Syangja', 'Sunrise Photo Studio, from the film Basanta weds Bindu', 'https://www.youtube.com/watch?v=2thTrQR3pec', '', '', 3, '[{"id":"1-book-as-soon-as-the-date-is-fixed","text":"1. Book as soon as the date is fixed","depth":2},{"id":"2-decide-what-you-want-to-keep","text":"2. Decide what you want to keep","depth":2},{"id":"3-share-the-schedule-a-week-before","text":"3. Share the schedule a week before","depth":2},{"id":"4-name-one-family-coordinator","text":"4. Name one family coordinator","depth":2},{"id":"5-plan-the-group-photos","text":"5. Plan the group photos","depth":2},{"id":"6-think-about-light","text":"6. Think about light","depth":2},{"id":"7-on-the-day","text":"7. On the day","depth":2},{"id":"8-after-the-wedding","text":"8. After the wedding","depth":2}]'::jsonb) on conflict do nothing;

commit;
